export * from '../modules/auth/domain/repositories/session.repository';
export * from '../modules/class/domain/repositories/class.repository';
export * from '../modules/coordinator/domain/repositories/coordinator.repository';
export * from '../modules/course/domain/repositories/course.repository';
export * from '../modules/semester/domain/repositories/semester.repository';
export * from '../modules/subject-teacher-semester/domain/repositories/subject-teacher-semester.repository';
export * from '../modules/subject/domain/repositories/subject.repository';
export * from '../modules/teacher/domain/repositories/teacher.repository';
export * from '../modules/user/domain/repositories/user.repository';
