services:
  asgen-database:
    image: 'postgres:18-alpine'
    container_name: asgen-database
    networks:
      - asgen-network
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: ${DB_NAME}
    restart: unless-stopped
    profiles:
      - prd
      - dev

  api-prd:
    image: 'asgen-api-prd:latest'
    build:
      context: .
      dockerfile: Dockerfile
    container_name: asgen-api-prd
    networks:
      - asgen-network
    ports:
      - '${PORT}:${PORT}'
    env_file:
      - .env
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d mydb"]
      interval: 5s
      timeout: 5s
      retries: 5
    profiles:
      - prd
    depends_on:
      asgen-database:
        condition: service_healthy

  api-dev:
    image: 'asgen-api-dev:latest'
    user: '${UID}:${GID}'
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: asgen-api-dev
    networks:
      - asgen-network
    ports:
      - '0.0.0.0:${PORT}:${PORT}'
    env_file:
      - .env
    restart: unless-stopped
    profiles:
      - dev
    depends_on:
      asgen-database:
        condition: service_healthy
    volumes:
      - type: bind
        source: .
        target: /app

networks:
  asgen-network:
    driver: bridge
