services:
  asgen-database:
    image: 'postgres:17-alpine'
    container_name: asgen-database
    networks:
      - asgen-network
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: ${DB_NAME}
    restart: unless-stopped
    profiles:
      - prd
      - dev

  api-prd:
    image: 'asgen-api-prd:latest'
    build:
      context: .
      dockerfile: Dockerfile
    container_name: asgen-api-prd
    networks:
      - asgen-network
    ports:
      - "${PORT}:${PORT}"
    env_file:
      - .env
    restart: unless-stopped
    profiles:
      - prd
    depends_on:
      - asgen-database

  api-dev:
    image: 'asgen-api-dev:latest'
    user: "${UID}:${GID}"
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: asgen-api-dev
    networks:
      - asgen-network
    ports:
      - "${PORT}:${PORT}"
    env_file:
      - .env
    restart: unless-stopped
    profiles:
      - dev
    depends_on:
      - asgen-database
    volumes:
      - type: bind
        source: .
        target: /app

networks:
  asgen-network:
    driver: bridge
