# FROM node:24-alpine AS runtime
FROM denoland/deno:alpine AS runtime

WORKDIR /app

RUN apk add nodejs npm && \
    npm install -g pnpm

COPY . .

ENV TZ=America/Sao_Paulo

RUN chmod +x /app/start.dev.sh

CMD ["sh", "/app/start.dev.sh"]
