onlyBuiltDependencies:
  - '@nestjs/core'
  - '@scarf/scarf'
  - argon2
  - esbuild
  - unrs-resolver
allowBuilds:
  '@nestjs/core': true
  '@scarf/scarf': true
  argon2: true
  esbuild: true
  unrs-resolver: true